ebooks/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views.generic import TemplateView

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("web.urls", namespace="web")),

]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

web/urls.py
# Create web/urls.py and paste the following
from django.urls import path
from . import views
from django.views.generic import TemplateView

app_name = "web"

urlpatterns = [
    path("shop_details/<int:id>/", views.shop_details, name="shop_details"),
    path("", views.shop, name="shop"),
    path("signup", views.signup, name="signup"),
    path("login", views.login_1, name="login"),
    path('logout', views.logout_view, name='logout'),

]

web/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class Product(models.Model):
    LANG_CHOICES = (
        ('eng', 'English'),
        ('mal', 'Malayalam'),
        ('ara', 'Arabic'),
    )
    language = models.CharField(max_length=3, choices=LANG_CHOICES)
    name=models.CharField(max_length=50)
    author=models.CharField(max_length=50)
    price=models.FloatField()
    year=models.IntegerField()
    image=models.ImageField(upload_to="")

    def __str__(self):
        return self.name
    




class Comment(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    content = models.TextField()
    product = models.ForeignKey(Product, on_delete=models.CASCADE)

    def __str__(self):
        return self.content

web/views.py
from django.shortcuts import render,redirect,get_object_or_404
from django.contrib.auth import authenticate,login,logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from .models import Product

from django.http import HttpResponse
from .models import Comment

from django.http import JsonResponse
# Create your views here.



from django.contrib.auth.decorators import login_required

from django.http import JsonResponse

def shop_details(request, id):
    product = get_object_or_404(Product, id=id)

    if request.method == 'POST':
        if request.user.is_authenticated:
            comment_content = request.POST.get('comment')
            if comment_content and comment_content.strip():
                comment = Comment(content=comment_content, product=product, user=request.user)
                comment.save()
                return JsonResponse({'success': True, 'username': request.user.username, 'comment': comment_content})
            else:
                return JsonResponse({'success': False, 'message': 'Comment cannot be empty.'})
        else:
            return JsonResponse({'success': False, 'message': 'Authentication required'})

    comments = Comment.objects.filter(product=product)
    context = {"product": product, 'comments': comments}
    return render(request, "web/shop-detail.html", context)



    






def shop(request):
    language_filter = request.GET.get('language', '')
    products = Product.objects.all()
    if language_filter:
        products = products.filter(language=language_filter)

    min_price = request.GET.get('min_price')
    max_price = request.GET.get('max_price')
    if min_price and max_price:
        products = products.filter(price__gte=min_price, price__lte=max_price)



    context = {"product": products, "request": request} # Pass the request object to the template context
    return render(request, "web/shop.html", context)




def signup(request):

    if request.method == "POST":
        username = request.POST.get('username')
        password1 = request.POST.get('password1')
        password2 = request.POST.get('password2')
        
        if password1 != password2:
            print('Passwords do not match')
            return redirect('web:signup')
        else:
            if User.objects.filter(username=username).exists():
                print('User already exists')
                return redirect('web:signup')
            else:
                user = User.objects.create_user(username=username, password=password1)
                return redirect('web:login')

    return render(request, 'web/signup.html')





def login_1(request,):

    if request.method=="POST":
        username = request.POST.get('username')
        password = request.POST.get('password')
        user =authenticate(request,username=username, password=password)
        if user is not None:
            login(request,user)
            return redirect('web:shop')
        else:  
            print('hi')
            return redirect('web:signup')
    return render(request,"web/login.html")



def logout_view(request):
    logout(request)
    return redirect('web:shop')

templates/web/shop-detail.html
{% load static %}

<!doctype html>
<html class="no-js" lang="zxx">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="meta description">

    <!-- Favicons -->
    <link rel="shortcut icon" href="{% static 'web/assets/img/favicon.ico" type="image/x-icon">
    <link rel="apple-touch-icon" href="{% static 'web/assets/img/icon' %}'">
    <title>Lazio - Multipurpose eCommerce Bootstrap 5 Template</title>

    <!-- ************************* CSS Files ************************* -->

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="{% static 'web/assets/css/bootstrap.css' %}">

    <!-- Font Awesome CSS -->
    <link rel="stylesheet" href="{% static 'web/assets/css/font-awesome.min.css' %}">

    <!-- All Plugins CSS css -->
    <link rel="stylesheet" href="{% static 'web/assets/css/plugins.css' %}">

    <!-- style css -->
    <link rel="stylesheet" href="{% static 'web/assets/css/main.css' %}">

    <!-- modernizr JS
    ============================================ -->
    <script src="{% static 'web/assets/js/vendor/modernizr-2.8.3.min.js' %}"></script>
    <!--[if lt IE 9]>
    <script src="//oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
    <script src="//oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->


    <!-- ************************* JS Files ************************* -->

    <!-- jQuery JS -->
    <script src="{% static 'web/assets/js/vendor/jquery.min.js' %}" defer></script>

    <!-- Bootstrap and Popper Bundle JS -->
    <script src="{% static 'web/assets/js/bootstrap.bundle.min.js' %}" defer></script>

    <!-- Plugins JS -->
    <script src="{% static 'web/assets/js/plugins.js' %}" defer></script>

    <!-- Ajax Mail JS -->
    <script src="{% static 'web/assets/js/ajax-mail.js' %}" defer></script>

    <!-- Main JS -->
    <script src="{% static 'web/assets/js/main.js' %}" defer></script>


{% comment %} <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css">

    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.7/dist/umd/popper.min.js" integrity="sha384-zYPOMqeu1DAVkHiLqWBUTcbYfZ8osu1Nd6Z89ify25QV9guujx43ITvfi12/QExE" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.min.js" integrity="sha384-Y4oOpwW3duJdCWv5ly8SCFYWqFDsfob/3GkgExXKV4idmbt98QcxXYs9UoXAB7BZ" crossorigin="anonymous"></script> {% endcomment %}

</head>

<body>


    <!-- Main Wrapper Start Here -->
    <div class="wrapper bg--zircon-light color-scheme-1">
        <!-- Header Area Start Here -->
        <header class="header header-1">
            <div class="header-top header-1--top">
                <div class="container">
                    <div class="row align-items-center">
                        <div class="col-lg-6 text-lg-start text-center">
                            <!-- Contact Info Start -->
                            <ul class="contact-info contact-info--1">   
                                <li class="contact-info__list"><i class="fa fa-envelope-open"></i><a href="mailto:demo@example.com">demo@example.com</a></li>  
                                <li class="contact-info__list"><i class="fa fa-phone"></i><a href="#">+0000000000</a></li>
                            </ul>
                            <!-- Contact Info End -->
                        </div>
                        <div class="col-lg-6 text-end">
                            <!-- Header Top Nav Start -->
                            <div class="header-top__nav header-top__nav--1 d-flex justify-content-lg-end justify-content-center">
                                <div class="user-info header-top__nav--item">
                                    <div class="dropdown header-top__dropdown">
                                        <a class="dropdown-toggle" id="userID" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                            My Account
                                        </a>
                                        <div class="dropdown-menu" aria-labelledby="userID">
                                            
                                            {% if user.is_authenticated %}
                                                 <a class="dropdown-item" href="{% url 'web:logout' %}">Logout</a>
                                             {% else %}
                                                  <a class="dropdown-item" href="{% url 'web:login' %}">Sign In</a>
                                            {% endif %}
                                        </div>
                                    </div>
                                </div>
                                <div class="currency-selector header-top__nav--item">
                                    <div class="dropdown header-top__dropdown">
                                      
                                    </div>
                                </div>
                                <div class="language-selector header-top__nav--item">
                                    
                                </div>
                            </div>
                            <!-- Header Top Nav End -->                        
                        </div>
                    </div>
                </div>
            </div>
           

            <!-- Sticky Header Start -->
           
            <!-- Sticky Header End -->
        </header>
        <!-- Header Area End Here -->

        <div class="breadcrumb-area">
 
        </div>
        <!-- Main Wrapper Start -->
  


        <div class="product-box product-box-hover-down bg--white color-1">

            <h1>{{product.name}}</h1>
            <div class="product-box__img">
                <img src="{{product.image.url}}" alt="product" class="primary-image">
                <img src="{{product.image.url}}" alt="product" class="secondary-image">
                {% comment %} <a href="#" data-bs-toggle="modal" data-bs-target="#productModal" class="product-box__quick-view"><i class="fa fa-search"></i></a> {% endcomment %}
            </div>
            <div class="product-box__content">
                <h3 class="product-box__title"><a href=""></a></h3>
                <div class="ratings">
                    <p>author:{{product.author}}</p>
                    <p>publish year:{{product.year}}</p>
                    <p>lng:{{product.language}}</p>
                </div>

                <div class="product-box__price">
                    <span class="regular-price"></span>
                    <span class="sale-price">{{product.price}}</span>
                </div>
            </div>



        </div>


        
        
        </div>

        <div id="pdf">
            <a href="{% static 'web/assets/Moksh About page.pdf' %}" download class="pdf-download-button"><button><h2>Download PDF</h2> </button></a>
            <a href="{% static 'web/assets/Moksh About page.pdf' %}"  class="pdf-download-button"><button><h2>open now</h2> </button></a>
        </div>
  



        <button class="open-overlay-button">Open Overlay</button>


        <script src="https://cdnjs.cloudflare.com/ajax/libs/pdf.js/2.9.359/pdf.min.js"></script>

<div id="overlay" class="overlay">
  <div class="overlay-content">
    <object data="{% static 'web/assets/Moksh About page.pdf' %}" type="application/pdf" width="100%" height="100%">
      <p>Your browser does not support PDF embedding. You can <a download href="{% static 'web/assets/Moksh About page.pdf' %}">download the PDF</a> instead.</p>
    </object>
    <button class="close-overlay-button">Close</button>
  </div>
</div>

<style>
  .overlay {
    position: fixed;
    top: 0;
    left: 0;
    width: 100%;
    height: 100%;
    background-color: rgba(0, 0, 0, 0.8);
    display: none;
    justify-content: center;
    align-items: center;
  }

  .overlay-content {
    background-color: white;
    padding: 20px;
    max-width: 500px;
    max-height: 80%;
    overflow-y: auto;
  }

  .open-overlay-button {
    background-color: #007bff;
    color: white;
    padding: 10px 20px;
    border: none;
    border-radius: 4px;
    cursor: pointer;
  }

  .open-overlay-button:hover {
    background-color: #0056b3;
  }
  
  .close-overlay-button {
    background-color: #007bff;
    color: white;
    padding: 10px 20px;
    border: none;
    border-radius: 4px;
    cursor: pointer;
    margin-top: 10px;
  }

  .close-overlay-button:hover {
    background-color: #0056b3;
  }
  #pdf{
    display:flex;
    flex-direction:column;
  }
</style>

<script>
  document.querySelector('.open-overlay-button').addEventListener('click', function() {
    document.getElementById('overlay').style.display = 'flex';
  });

  document.querySelector('.close-overlay-button').addEventListener('click', function() {
    document.getElementById('overlay').style.display = 'none';
  });
</script>



<br><br><br>

<style>
    #comment{ 
        width: 50%;
        height: 66px;}
    {% comment %} #comment_section{
        height: 200px;
        overflow-y:scroll;
        padding: 5px 50px 0px;
        
        margin-bottom: 30px;
    }
    #comment_section p{
color:black;
font-size:20px;
    } {% endcomment %}
    .popup-message {
        display: none;
        position: fixed;
        top: 50%;
        left: 50%;
        transform: translate(-50%, -50%);
        background-color: #000;
        padding: 20px;
        border-radius: 5px;
        box-shadow: 0 2px 4px rgba(0, 0, 0, 0.2);
        color:#fff;
    }
    form#comment-form {
        display: flex;
        justify-content: center;
    }
    #add_comment{
        background: #007bff;
    color: white;
    padding: 5px;
    }
    {% comment %} #comments-container{
        background-color: gray;padding-left:20px;
    } {% endcomment %}
    #h1cmnt{
        text-align:center;
    }
    #dsblcmnt{
        display: flex;
        justify-content: center;
    }
    #comment_section {
        margin-top: 20px;
    }

    #comments-container {
        background-color: #f5f5f5;
        padding: 10px;
        border-radius: 5px;
    }

    #cmntbrd {
        margin-bottom: 10px;
        padding: 10px;
        background-color: #ffffff;
        border: 1px solid #e0e0e0;
        border-radius: 5px;
    }

    #cmntbrd p:first-child {
        font-weight: bold;
        margin-bottom: 5px;
    }

    #cmntbrd p:last-child {
        margin-bottom: 0;
    }
    
</style>



<h1 id="h1cmnt">Comments</h1>

{% if user.is_authenticated %}
<form id="comment-form" method="POST" action="{% url 'web:shop_details' product.id %}">
    {% csrf_token %}
    <input id="comment" name="comment" placeholder="Comment here" type="text">
    <button id="add_comment" type="submit">Add Comment</button>
</form>
{% else %}
<div id="dsblcmnt">
    <input id="comment" name="comment" placeholder="Please login to comment" type="text" disabled>
    <a href="{% url 'web:login' %}"><button id="add_comment" type="">Login</button></a>
</div>
{% endif %}

<div id="popup-message" class="popup-message">
    Comment added successfully!
</div>

<br>

<div id="comment_section">
    <div id="comments-container">
        {% for comment in comments %}
        {% if comment.product == product %}
        <div id="cmntbrd">
            <p>{{ comment.user.username }}</p>
            <p>{{ comment.content }}</p>
        </div>
        {% endif %}
        {% endfor %}
    </div>
</div>


<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script>
    $(document).ready(function () {
        $('#comment-form').submit(function (event) {
            event.preventDefault();
            var commentContent = $('#comment').val();
            $.ajax({
                url: $(this).attr('action'),
                type: 'POST',
                data: {
                    'comment': commentContent,
                    'csrfmiddlewaretoken': $('input[name=csrfmiddlewaretoken]').val()
                },
                success: function (response) {
                    if (response.success) {
                        $('#comment').val('');
                        var newComment = '<div id="cmntbrd"><p>' + response.username + '</p><p>' + response.comment + '</p></div>';
                        $('#comments-container').prepend(newComment); // Prepend the new comment
                        $('#popup-message').fadeIn().delay(2000).fadeOut(); // Show popup message
                    }
                }
            });
        });
    });
    
</script>






     
        <!-- Scroll To Top -->
        
      
        <!-- Modal -->
        

    </div>
    <!-- Main Wrapper End Here -->

</body>

</html>